#!/bin/bash
#####################################################
#author: "Andreas Tigasing; andreas.tigasing@khk.ee"#
#####################################################
#Varvid#
########
red='\033[0;31m'
nc='\033[0m'
########

#sisend

read -p "Sisesta aja vaartus: " aeg

######################################################

if [ $aeg -ge 6 ] && [ $aeg -lt 12 ]
then
	echo "Tere Hommikust!"
elif [ $aeg -ge 12 ] && [ $aeg -lt 18 ]
then
	echo "Tere Päevast!"
elif [ $aeg -ge 18 ] && [ $aeg -lt 22 ]
then
	echo "Tere Õhtust!"
elif [ $aeg -ge 22 ] && [ $aeg -lt 24 ] 
then
	echo "Head ööd!"
elif [ $aeg -ge 0 ] && [ $aeg -lt 6 ]
then
	echo "Head ööd!"
fi
