#! /bin/bash
#
#

echo -n "Sisesta ridade arv: "; read ridu #loeb sisestatud ridade arvu
echo -n "Sisesta tärnide arv: "; read tarnid #loeb sisestatud tärnide arvu
reanum=1
for (( i = 1; i <= $ridu; i++ )) #alustab tsükkliga
do #alustab do käsuga
	echo -n "$reanum."
	let reanum++
	for (( j = 1; i <= $tarnid; j++ ))
	do
		if (($i == 1 || $i == $ridu)); then
			echo -n "* "
		elif (($j == 1 || $j == $tarnid)); then
			echo -n "* "
		else
			echo -n "  "
		fi
	done
	echo ""
done #lõpetab do käsu

