#!/bin/bash
#
#

echo -n "Sisesta ridade arv: "; read rida #loeb ridade arvu
reanum=1

for (( i == 1; i <= $read; i++ )) #tsukkli algus
do #alustab do kasuga
	echo -n "$reanum." #echob readnumbri
	tarne=$(($rida + 1 - $i)) #arvutus
	let reanum++
	for (( j = 1; j <= $tarne; j++ ))
	do
		echo -n "* "
	done #lõpetab do kasu
	echo ""
done #lõpetab do kasu

